wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678379939.085539
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.7.13
      5: 0.13.11
      8:
      - 5
